add-fft
YNUCPC/ynu-icpc-library pull request #25
Opened 2021-11-01 02:45 UTC by M4c4r0n

テスト用問題でよいものが見つからないため、とりあえずテスト以外を書きました。
gitのことでも何でも間違いあれば指摘してくださると助かります。

2021-11-01 04:54 UTC, noss3885 requested changes
PDF上の見え方についていくつかレビューしてみました。確認お願いします。

2021-11-01 04:54 UTC, noss3885 commented on docs/math/FFT.tex
> +・convolution(a,b):長さ$n$の整数列$a$,長さ$m$の整数列$b$の畳み込みを$O((n+m)log(n+m))$で計算する。畳み込み後の配列の要素がすべてdoubleに収まる必要がある。
箇条書きはLaTeXのitemize環境などを使用すると良いと思います

```suggestion
\begin{itemize}
    \item encode(a):整数型の配列$a$をstd::complex型に変換。
    \item decode(a):std::complex型の配列$a$を64bit整数型に変換。配列の要素毎に実部を丸めて整数に変換している。
    \item FFT(a):std::complex型で長さ$n$の配列$a$をフーリエ変換する。整数型の配列は引数にとれないため、encode(a),decode(a)等で適宜変換を行うこと。
    \item convolution(a,b):長さ$n$の整数列$a$,長さ$m$の整数列$b$の畳み込みを$O((n+m)\log(n+m))$で計算する。畳み込み後の配列の要素がすべてdoubleに収まる必要がある。
\end{itemize}
```

2021-11-01 04:54 UTC, noss3885 commented on docs/math/FFT.tex
> +\lstinputlisting{src/math/FFT.hpp}
fisrtlineで開始位置を指定すると `#include` 部分などをカットできます

```suggestion
\lstinputlisting[firstline=5]{src/math/FFT.hpp}
```

2021-11-01 04:54 UTC, noss3885 commented on src/math/FFT.hpp
> +//整数配列を複素数へ
`//` と日本語の間には空白を入れないと文字の色が適用されないようです

![image](https://user-images.githubusercontent.com/28915482/139622965-864c0b02-6f87-48fb-934f-a01b82bd10d2.png)


```suggestion
// 整数配列を複素数へ
```

2021-11-01 04:54 UTC, noss3885 commented on src/math/FFT.hpp
> +//複素数配列を整数へ
```suggestion
// 複素数配列を整数へ
```

2021-11-01 04:54 UTC, noss3885 commented on src/math/FFT.hpp
> +//非再帰
```suggestion
// 非再帰
```

2021-11-01 07:07 UTC, noss3885 commented
FFTのテストを追加しました

2021-11-02 06:06 UTC, M4c4r0n commented
遅くなってしまいすみません。suggestionをすべてcommitさせていただきました><

2021-11-02 06:08 UTC, noss3885 approved these changes

2021-11-02 06:09 UTC, noss3885 commented
大丈夫そうなのでマージします

2021-11-02 06:10 UTC, merged